import pandas as pd

def load_sales_data(filename="sales.csv"):
    """Loads sales data from a CSV file into a pandas DataFrame.
    Args:
        filename (str): The name of the CSV file containing sales data.
    Returns:
        pd.DataFrame: A DataFrame containing the sales data.
    """
    try:
        sales_data = pd.read_csv(filename)
        
        sales_data['sale_date'] = pd.to_datetime(sales_data['sale_date'], errors='coerce')
        return sales_data
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return None
    except pd.errors.EmptyDataError:
        print(f"Error: The file '{filename}' is empty.")
        return None
    except pd.errors.ParserError:
        print(f"Error: The file '{filename}' could not be parsed.")
        return None
    




def total_revenue(sales_data):
    """Calculates the total revenue from the sales data.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
    Returns:
        float: The total revenue calculated from the sales data.
    """    
    if sales_data is None:
        return 0.0
    total_revenue = sales_data['amount_paid'].sum()
    return total_revenue

def revenue_by_package(sales_data):
    """Calculates the total revenue generated by each package type.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
    Returns:
        pd.Series: A Series containing the total revenue for each package type.
    """
    if sales_data is None:
        return pd.Series(dtype=float)
    revenue_by_package = sales_data.groupby('pkg_name')['amount_paid'].sum().sort_values(ascending=False)
    return revenue_by_package

def revenue_by_month(sales_data):
    """Calculates the total revenue generated in each month.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
    Returns:
        pd.Series: A Series containing the total revenue for each month.
    """
    if sales_data is None:
        return pd.Series(dtype=float)
    sales_data['month'] = pd.to_datetime(sales_data['sale_date']).dt.to_period('M')
    revenue_by_month = sales_data.groupby('month')['amount_paid'].sum().sort_index()
    return revenue_by_month

def top_customers(sales_data, n=5):
    """Identifies the top N customers based on total revenue.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
        n (int): The number of top customers to return.
    Returns:
        pd.Series: A Series containing the total revenue for the top N customers.
    """
    if sales_data is None:
        return pd.Series(dtype=float)
    top_customers = sales_data.groupby('customer_name')['amount_paid'].sum().nlargest(n)
    return top_customers


def average_sale_value(sales_data):
    """Calculates the average sale value from the sales data.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
    Returns:
        float: The average sale value calculated from the sales data.
    """
    if sales_data is None:
        return 0.0
   
    average_value = sales_data['amount_paid'].mean()
    return average_value

def busiest_month(sales_data):
    """Identifies the month with the highest total sales.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
    Returns:
        str: The month with the highest total sales in 'YYYY-MM' format.
    """
    if sales_data is None:
        return None
    sales_data['month'] = pd.to_datetime(sales_data['sale_date']).dt.to_period('M')
    sales_by_month = sales_data.groupby('month')['amount_paid'].count()
    busiest_month = sales_by_month.idxmax()
    return str(busiest_month)

def profit_summary(sales_data):
    """Calculates the total profit from the sales data based on a given cost per unit.
    Args:
        sales_data (pd.DataFrame): A DataFrame containing the sales data.
    Returns:
        float: The total profit calculated from the sales data.
    """   
    if sales_data is None:
        return 0.0
    sales_data['profit'] = sales_data['amount_paid'] - sales_data['pkg_cost']
    total_profit = sales_data['profit'].sum()
    average_profit_per_sale = sales_data['profit'].mean()
    profit_by_package = sales_data.groupby('pkg_name')['profit'].sum().sort_values(ascending=False)
    return total_profit, average_profit_per_sale, profit_by_package


